type MockedUserDataType = { name: string; email: string };

const mockedUser = {
  name: "Anastasiia",
  email: "ana_stasiia@gmail.com",
};

type MockedHabitsType = [name: string, start_date: string, isCompleted: any];

const mockedHabits = [
  {
    name: "drink 8 glasses of water",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
  {
    name: "workout",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
  {
    name: "workout",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
  {
    name: "workout",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
  {
    name: "workout",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
  {
    name: "workout",
    start_date: "123",
    isCompleted: {
      1: true,
      2: true,
      3: true,
      4: false,
      5: true,
      6: true,
      7: true,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
    },
  },
];

export { mockedUser, mockedHabits };
export type { MockedHabitsType, MockedUserDataType };
